### ISSUE TITLE
Shading of Friday, date clicking is right-shifted

### ISSUE THREAD

**Issue by cgranier** [sharat87/just-a-calendar#2]
Tried this on Windows 11 & Edge Version 100.0.1185.29 (Official build) (64-bit)

- Friday and Saturday appear shaded, instead of Saturday and Sunday.
- To mark any date I must click on the next date.
- Number of days are wrong: January shows 28, February 31, etc.

**Comment by sharat87** [comment]
Hey, thank you so much for reporting. This should be fixed now.
